"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <div className="min-h-screen flex flex-col">
          {/* Top Navbar */}
          <header className="bg-white border-b shadow-sm">
            <div className="max-w-7xl mx-auto px-4 py-3 flex justify-between items-center">
              <div className="text-xl font-bold text-gray-700">My Next Kit</div>
              {/* Desktop Nav */}
              <nav className="hidden md:flex space-x-4 text-gray-600">
                <a href="./" className="hover:text-purple-600">
                  Home
                </a>
                <a href="#" className="hover:text-purple-600">
                  Transfers
                </a>
                <a href="#" className="hover:text-purple-600">
                  Players
                </a>
                <a href="#" className="hover:text-purple-600">
                  Clubs
                </a>
                <a href="#" className="hover:text-purple-600">
                  News
                </a>
              </nav>

              {/* Mobile Menu Toggle */}
              <button
                className="md:hidden text-gray-600 focus:outline-none"
                onClick={() => setIsOpen(!isOpen)}
              >
                <svg
                  className="w-6 h-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d={
                      isOpen
                        ? "M6 18L18 6M6 6l12 12"
                        : "M4 6h16M4 12h16M4 18h16"
                    }
                  />
                </svg>
              </button>
            </div>

            {/* Mobile Dropdown Menu */}
            {isOpen && (
              <div className="md:hidden px-4 pb-4 space-y-2 bg-white text-gray-600">
                <a href="#" className="block hover:text-purple-600">
                  Home
                </a>
                <a href="#" className="block hover:text-purple-600">
                  Transfers
                </a>
                <a href="#" className="block hover:text-purple-600">
                  Players
                </a>
                <a href="#" className="block hover:text-purple-600">
                  Clubs
                </a>
                <a href="#" className="block hover:text-purple-600">
                  News
                </a>
              </div>
            )}
          </header>

          {/* Main Content */}
          <main className="flex-1 bg-gradient-to-b from-white to-violet-50">
            {children}
          </main>

          {/* Bottom Nav Placeholder */}
          <footer className="bg-violet-100 border-t shadow-sm  py-4 text-sm text-gray-500 text-center">
            © 2025 My Next Kit. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
