"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const [isOpen, setIsOpen] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}

//  <div className="min-h-screen flex flex-col">
//           {/* Enhanced Background Elements */}
//           <div className="fixed inset-0 overflow-hidden pointer-events-none">
//             <div className="absolute -top-1/2 -right-1/2 w-96 h-96 bg-gradient-to-br from-blue-500/20 to-indigo-600/20 rounded-full blur-3xl animate-pulse"></div>
//             <div className="absolute -bottom-1/2 -left-1/2 w-96 h-96 bg-gradient-to-br from-purple-500/20 to-pink-600/20 rounded-full blur-3xl animate-pulse"></div>
//             <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-gradient-to-br from-emerald-500/10 to-teal-600/10 rounded-full blur-3xl animate-pulse"></div>
//           </div>

//           {/* Enhanced Top Navbar */}
//           <header className="relative bg-gradient-to-r from-slate-900/90 via-slate-800/90 to-slate-900/90 backdrop-blur-2xl border-b border-slate-700/50 shadow-2xl">
//             <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
//               <div className="text-2xl font-black text-white">
//                 My Next{" "}
//                 <span className="text-transparent bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-400 bg-clip-text">
//                   Kit
//                 </span>
//               </div>

//               {/* Desktop Nav */}
//               <nav className="hidden md:flex space-x-8 text-slate-300">
//                 <a
//                   href="./"
//                   className="hover:text-blue-400 transition-all duration-300 font-medium hover:scale-105 transform relative group"
//                 >
//                   Home
//                   <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-400 to-indigo-400 transition-all duration-300 group-hover:w-full"></span>
//                 </a>
//                 <a
//                   href="#"
//                   className="hover:text-blue-400 transition-all duration-300 font-medium hover:scale-105 transform relative group"
//                 >
//                   Transfers
//                   <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-400 to-indigo-400 transition-all duration-300 group-hover:w-full"></span>
//                 </a>
//                 <a
//                   href="#"
//                   className="hover:text-blue-400 transition-all duration-300 font-medium hover:scale-105 transform relative group"
//                 >
//                   Players
//                   <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-400 to-indigo-400 transition-all duration-300 group-hover:w-full"></span>
//                 </a>
//                 <a
//                   href="#"
//                   className="hover:text-blue-400 transition-all duration-300 font-medium hover:scale-105 transform relative group"
//                 >
//                   Clubs
//                   <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-400 to-indigo-400 transition-all duration-300 group-hover:w-full"></span>
//                 </a>
//                 <a
//                   href="#"
//                   className="hover:text-blue-400 transition-all duration-300 font-medium hover:scale-105 transform relative group"
//                 >
//                   News
//                   <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-400 to-indigo-400 transition-all duration-300 group-hover:w-full"></span>
//                 </a>
//               </nav>

//               {/* Mobile Menu Toggle */}
//               <button
//                 className="md:hidden text-slate-300 focus:outline-none hover:text-blue-400 transition-colors duration-300 p-2 rounded-lg hover:bg-slate-800/50"
//                 onClick={() => setIsOpen(!isOpen)}
//               >
//                 <svg
//                   className="w-6 h-6"
//                   fill="none"
//                   stroke="currentColor"
//                   viewBox="0 0 24 24"
//                 >
//                   <path
//                     strokeLinecap="round"
//                     strokeLinejoin="round"
//                     strokeWidth={2}
//                     d={
//                       isOpen
//                         ? "M6 18L18 6M6 6l12 12"
//                         : "M4 6h16M4 12h16M4 18h16"
//                     }
//                   />
//                 </svg>
//               </button>
//             </div>

//             {/* Enhanced Mobile Dropdown Menu */}
//             {isOpen && (
//               <div className="md:hidden px-4 pb-6 space-y-3 bg-slate-900/95 backdrop-blur-xl border-t border-slate-700/50">
//                 <a
//                   href="#"
//                   className="block py-3 px-4 hover:text-blue-400 transition-all duration-300 font-medium rounded-lg hover:bg-slate-800/50"
//                 >
//                   Home
//                 </a>
//                 <a
//                   href="#"
//                   className="block py-3 px-4 hover:text-blue-400 transition-all duration-300 font-medium rounded-lg hover:bg-slate-800/50"
//                 >
//                   Transfers
//                 </a>
//                 <a
//                   href="#"
//                   className="block py-3 px-4 hover:text-blue-400 transition-all duration-300 font-medium rounded-lg hover:bg-slate-800/50"
//                 >
//                   Players
//                 </a>
//                 <a
//                   href="#"
//                   className="block py-3 px-4 hover:text-blue-400 transition-all duration-300 font-medium rounded-lg hover:bg-slate-800/50"
//                 >
//                   Clubs
//                 </a>
//                 <a
//                   href="#"
//                   className="block py-3 px-4 hover:text-blue-400 transition-all duration-300 font-medium rounded-lg hover:bg-slate-800/50"
//                 >
//                   News
//                 </a>
//               </div>
//             )}
//           </header>

//           {/* Enhanced Main Content */}
//           <main className="flex-1 relative bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
//             {children}
//           </main>

//           {/* Enhanced Footer */}
//           <footer className="relative bg-gradient-to-r from-slate-900/95 via-slate-800/95 to-slate-900/95 backdrop-blur-xl border-t border-slate-700/50 py-8">
//             <div className="max-w-7xl mx-auto px-4">
//               <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
//                 {/* Footer Logo */}
//                 <div className="text-xl font-black text-white">
//                   My Next{" "}
//                   <span className="text-transparent bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-400 bg-clip-text">
//                     Kit
//                   </span>
//                 </div>

//                 {/* Footer Links */}
//                 <div className="flex space-x-6 text-slate-400">
//                   <a href="#" className="hover:text-blue-400 transition-colors duration-300 text-sm">
//                     Privacy Policy
//                   </a>
//                   <a href="#" className="hover:text-blue-400 transition-colors duration-300 text-sm">
//                     Terms of Service
//                   </a>
//                   <a href="#" className="hover:text-blue-400 transition-colors duration-300 text-sm">
//                     Contact
//                   </a>
//                 </div>

//                 {/* Social Links */}
//                 <div className="flex space-x-4">
//                   <a href="#" className="w-10 h-10 bg-slate-800/50 rounded-lg flex items-center justify-center hover:bg-blue-500/20 hover:text-blue-400 transition-all duration-300 hover:scale-110 transform">
//                     <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
//                       <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
//                     </svg>
//                   </a>
//                   <a href="#" className="w-10 h-10 bg-slate-800/50 rounded-lg flex items-center justify-center hover:bg-blue-500/20 hover:text-blue-400 transition-all duration-300 hover:scale-110 transform">
//                     <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
//                       <path d="M22.46 6c-.77.35-1.6.58-2.46.69.88-.53 1.56-1.37 1.88-2.38-.83.5-1.75.85-2.72 1.05C18.37 4.5 17.26 4 16 4c-2.35 0-4.27 1.92-4.27 4.29 0 .34.04.67.11.98C8.28 9.09 5.11 7.38 3 4.79c-.37.63-.58 1.37-.58 2.15 0 1.49.75 2.81 1.91 3.56-.71 0-1.37-.2-1.95-.5v.03c0 2.08 1.48 3.82 3.44 4.21a4.22 4.22 0 0 1-1.93.07 4.28 4.28 0 0 0 4 2.98 8.521 8.521 0 0 1-5.33 1.84c-.34 0-.68-.02-1.02-.06C3.44 20.29 5.7 21 8.12 21 16 21 20.33 14.46 20.33 8.79c0-.19 0-.37-.01-.56.84-.6 1.56-1.36 2.14-2.23z"/>
//                     </svg>
//                   </a>
//                   <a href="#" className="w-10 h-10 bg-slate-800/50 rounded-lg flex items-center justify-center hover:bg-blue-500/20 hover:text-blue-400 transition-all duration-300 hover:scale-110 transform">
//                     <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
//                       <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.748-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24.009 12.017 24.009c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001 12.017.001z"/>
//                     </svg>
//                   </a>
//                 </div>
//               </div>

//               {/* Copyright */}
//               <div className="mt-8 pt-6 border-t border-slate-700/50 text-center">
//                 <p className="text-slate-400 text-sm">
//                   © 2025 My Next Kit. All rights reserved. | Built with passion for football fans worldwide.
//                 </p>
//               </div>
//             </div>
//           </footer>
//         </div>
